### ISSUE TITLE
Humble, Jazzy, and Rolling Release Task List

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros#195]
## Bugfixes

**py_trees**

* [x] https://github.com/splintered-reality/py_trees/pull/383
* [x] https://github.com/splintered-reality/py_trees/pull/366
* [x] https://github.com/splintered-reality/py_trees/pull/359

**py_trees_ros_interfaces**

* [x] [float32->float64 in snapshot_period &rarr; compatible bounds with python's float](https://github.com/splintered-reality/py_trees_ros_interfaces/commit/353731f94d006ce0bc9be91a965cf41662b95ff0)

**py_trees_ros**

* [x] #196
* [x] #194 
* [x] #191
* [x] #201
* [x] #204

**py_trees_ros_tutorials**

* [x] https://github.com/splintered-reality/py_trees_ros_tutorials/pull/49
* [x] https://github.com/splintered-reality/py_trees_ros_tutorials/pull/48
* [x] https://github.com/splintered-reality/py_trees_ros_tutorials/pull/47

## New Features / Breaking Changes

**py_trees**

* [x] https://github.com/splintered-reality/py_trees/issues/373
* [x] https://github.com/splintered-reality/py_trees/issues/352
  * `Sequence(memory=False)` (experimental&rarr;final)
  * `Selector(memory=True)` (experimental&rarr;final)
* [x] https://github.com/splintered-reality/py_trees/issues/364
  * `decorators.Repeat` (added)
  * `decorators.Retry` (added)
* [x] https://github.com/splintered-reality/py_trees/pull/376
  * `decorators.Count` (added)
  * `behaviours.Count` (removed &rightarrow; use `behaviours.StatusQueue` + `decorators.Count`)
* [x] https://github.com/splintered-reality/py_trees/issues/333
  * `idioms.eternal_guard` (removed &rightarrow; use `Sequence(memory=False)`)
* [x] https://github.com/splintered-reality/py_trees/issues/367
  * `behaviours.StatusSequence` &rightarrow; `behaviours.StatusQueue` (changed)

**py_trees_ros**

* [x] https://github.com/splintered-reality/py_trees_ros/pull/188
  * `tree.setup(node, node_name)` (added)
* [x] #212 
  * `tree.setup(node, node_name, timeout, my_custom_arg="foo")` (added)

## General Improvements

**py_trees**

* [x] https://github.com/splintered-reality/py_trees/pull/360
* [x] https://github.com/splintered-reality/py_trees/pull/375

**py_trees_ros**

* [x] #187 (eliminates deprecation warnings)

## Development Environment

**py_trees**
  * [x] https://github.com/splintered-reality/py_trees/pull/380
  * [x] https://github.com/splintered-reality/py_trees/pull/386
  * [x] https://github.com/splintered-reality/py_trees/pull/396
  * [x] https://github.com/splintered-reality/py_trees/pull/397
  * [x] https://github.com/splintered-reality/py_trees/pull/389
  * [x] https://github.com/splintered-reality/py_trees/pull/391
  * [x] webhook check
  * [x] update README

**py_trees_ros**
  * [x] #183 (for foxy)
  * [x] #192
  * [x] #200
  * [x] webhook check, #207, #208
  * [x] #202
    * [ ] update README for py_trees_ros_tutorials, py_trees_js and py_trees_ros_viewer

**py_trees_ros_interfaces**
  * [ ] webhook check
  * [x] update README

**py_trees_js**
  * [x] https://github.com/splintered-reality/py_trees_js/pull/143
  * [x] circleci -> github actions
    * [x] https://github.com/splintered-reality/py_trees_js/pull/144
    * [x] https://github.com/splintered-reality/py_trees_js/pull/146
  * [x] update README
  * [x] webhook check

**py_trees_ros_tutorials**
  * [x] upgrade sphinx
  * [ ] circleci -> github actions
  * [ ] deprecate use of distutils
  * [ ] check tutorials
  * [x] update README

**py_trees_ros_viewer**
  * [ ] devcontainers
  * [ ] poetry
  * [x] update README
  * [x] webhook check

## Release

* [x] py_trees (2.2.3) - [github](https://github.com/splintered-reality/py_trees/releases/tag/2.2.2), [pypi](https://pypi.org/project/py-trees/), [read-the-docs](https://py-trees.readthedocs.io/en/release-2.2.x/),  [humble](https://repo.ros2.org/status_page/ros_humble_default.html?q=py_trees%24), [rolling](https://repo.ros2.org/status_page/ros_rolling_default.html?q=py_trees%24)
* [x] py_trees_js (0.6.4) - [github](https://github.com/splintered-reality/py_trees_js/tree/release/0.6.x), [pypi](https://pypi.org/project/py-trees-js/0.6.4/), [humble](https://repo.ros2.org/status_page/ros_humble_default.html?q=py_trees_js), [rolling](https://repo.ros2.org/status_page/ros_rolling_default.html?q=py_trees_js)
* [x] py_trees_ros_interfaces (2.1.0) - [humble](https://repo.ros2.org/status_page/ros_humble_default.html?q=py_trees_ros_interfaces), [rolling](https://repo.ros2.org/status_page/ros_rolling_default.html?q=py_trees_ros_interfaces)
* [x] py_trees_ros (2.2.2) - [github](https://github.com/splintered-reality/py_trees_ros/tree/release/2.2.x), [read-the-docs](https://py-trees-ros.readthedocs.io/en/release-2.2.x/), [humble](https://repo.ros2.org/status_page/ros_humble_default.html?q=py_trees_ros), [rolling](https://repo.ros2.org/status_page/ros_rolling_default.html?q=py_trees_ros)
* [x] py_trees_ros_viewer - humble, rolling
* [x] py_trees_ros_tutorials - read-the-docs, humble, rolling
* [ ] Discourse advertisement

**Comment by boilerbots** [comment]
When will py-tree and py-tree-ros show up in rosdep for Humble?

**Comment by stonier** [comment]
> When will py-tree and py-tree-ros show up in rosdep for Humble?

Completely depends on the ros team and when they roll out a release.

You can keep an eye on it [here](https://repo.ros2.org/status_page/ros_humble_default.html?q=py_trees). When the last box goes from red to green, it's been released.

You can also point your apt source to the staging apt server if you can't wait (or you just want to road test them). They're over at http://packages.ros.org/. It used to be called `ros-shadow-fixed`. Looks like you want `ros2-testing` now. You'll find the humble debs under there.

**Comment by VArt3m** [comment]
@stonier 
Hello! Sorry to bother you, is there any plans to port or solutions for running `py_trees_ros_viewer` on ROS2 Humble? I've tried downloading the source and building it - which kinda works, but webview area remains empty and does not load.
I really would appreciate any pointer on what could be wrong there or what be done to port this great tool to Humble.
Thanks in advance

**Comment by FranzEricSchneider** [comment]
Similarly, I'm trying to walk through the tutorials but the install steps are failing, my plan is to try to go backwards to Foxy for the tutorials, then maybe forward to Humble for usage unless the viewer seems critical.
```
E: Unable to locate package ros-humble-py-trees-ros-tutorials
E: Unable to locate package ros-humble-py-trees-ros-viewer
```

**Comment by sea-bass** [comment]
The task list isn't quite complete as specified, but I'm getting going with releases to Humble, Jazzy, and Rolling.

Most of what remains is developer experience stuff anyhow, which can be done orthogonally to the actual binary releases to the newer ROS distros.
