### ISSUE TITLE
ROS2 - Mock Robot Components

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros#51]
**Mock**

* [ ] Dynamic reconfigure replacements
* [ ] Mock Robot Dashboard
* [x] Battery &rarr; PR #46
* [x] LED Strip &rarr; PR #46 
* [x] LED Strip sans termcolor &rarr; PR #52
* [ ] Action Server
* [ ] Dock
* [ ] Move Base
* [ ] Rotate
* [ ] Safety Sensors

**Comment by stonier** [comment]
Issue migrated to https://github.com/splintered-reality/py_trees_ros_tutorials/issues/5
