### ISSUE TITLE
Documentation Redux

### ISSUE THREAD

**Issue by stonier** [splintered-reality/py_trees_ros#69]
* [x] re-sphinx &rarr; #80 
* [x] port for ros2 &rarr; #80 
* [x] documentation for py-trees-tree-watcher &rarr; #81  
* [x] automate on ~~ROS2 build farm~~, or read the docs  &rarr; #81, #82
